#import "~/base/queries/fragments/paragraphs/paragraphUnion.fragment.gql"

fragment paragraphFromLibrary on ParagraphFromLibrary {
  __typename
  reusableParagraph {
    paragraphs {
      ...ParagraphUnion
    }
  }
  composition {
    position {
      parentId
      region
    }
  }
}
