fragment paragraphImage on ParagraphImage {
  __typename
  image {
    ... on MediaImage {
      name
      mediaImage {
        url
        title
        alt
        height
        width
      }
    }
  }
  align
  composition {
    position {
      parentId
      region
    }
  }
}
