#!/usr/bin/env bash

if [ -z "$IS_DDEV_PROJECT" ]; then
  composer install --no-dev
  echo 0
fi

composer install

if [ ! -f "web/sites/default/settings.local.php" ]; then
  cp config/example.settings.local.php web/sites/default/settings.local.php
  echo "include \$app_root . '/' . \$site_path . '/settings.local.php';" >> web/sites/default/settings.php
fi
