#!/usr/bin/env bash

usage() {
  echo "Usage: $( basename -- "$0") [-y]"
  echo "  -y: Assume 'yes' as the answer to all prompts and run non-interactively."
  exit 1
}

while test $# != 0
do
    case "$1" in
    -y) ASSUME_YES=1 ;;
    *)  usage ;;
    esac
    shift
done


if [ ! -d "vendor/" ]; then
  ./.ddev/commands/web/build
fi

cd web || exit 1
DRUSH="../vendor/bin/drush"

if [ -n "$ASSUME_YES" ]; then
  IS_SURE="y"
else
  IFS= read -r -p "Are you sure you want to install the dev dependencies? [y/N] " IS_SURE
fi

if [ "$IS_SURE" != "y" ] && [ "$IS_SURE" != "Y" ]; then
  exit 0
fi

"$DRUSH" site:install nuxtify -y --site-name="Nuxtify" --account-name=root

if [ ! -f "../frontend/.env" ]; then
  cp ../frontend/.env.example ../frontend/.env
fi

API_KEY="$("$DRUSH" sql:query "SELECT api_key FROM users_field_data WHERE name='GraphQL API';")"

sed -e "s/BACKEND_API_KEY=\".*/BACKEND_API_KEY=\"$API_KEY\"/" -i ../frontend/.env
