#import "~/queries/fragments/metatags/metaTagLink.fragment.gql"
#import "~/queries/fragments/metatags/metaTagValue.fragment.gql"
#import "~/queries/fragments/metatags/metaTagProperty.fragment.gql"

#import "~/queries/fragments/paragraphs/paragraphLayout.fragment.gql"
#import "~/queries/fragments/paragraphs/paragraphTitle.fragment.gql"
#import "~/queries/fragments/paragraphs/paragraphSubtitle.fragment.gql"
#import "~/queries/fragments/paragraphs/paragraphTextarea.fragment.gql"
#import "~/queries/fragments/paragraphs/paragraphImage.fragment.gql"

fragment nodeBasicPage on NodeBasicPage {
  title
  showTitle
  metatag {
    ...metaTagLink
    ...metaTagValue
    ...metaTagProperty
  }
  layout {
    ...paragraphLayout
    ...paragraphTitle
    ...paragraphSubtitle
    ...paragraphTextarea
    ...paragraphImage
  }
  translations {
    url
    langcode {
      id
    }
  }
}
