#import "~/queries/fragments/metatags/metaTagLink.fragment.gql"
#import "~/queries/fragments/metatags/metaTagValue.fragment.gql"
#import "~/queries/fragments/metatags/metaTagProperty.fragment.gql"

#import "~/queries/fragments/paragraphs/paragraphUnion.fragment.gql"
#import "~/queries/fragments/paragraphs/paragraphFromLibrary.fragment.gql"

fragment nodeBasicPage on NodeBasicPage {
  title
  showTitle
  metatag {
    ...metaTagLink
    ...metaTagValue
    ...metaTagProperty
  }
  layout {
    ...ParagraphUnion
    ...paragraphFromLibrary
  }
  translations {
    path
    langcode {
      id
    }
  }
}
